### ISSUE TITLE
would you mind uploading the pothole datatset weights?

### ISSUE THREAD

**Issue by jamjamjon** [wangermeng2021/Scaled-YOLOv4-tensorflow2#7]
Can you upload the pothole datatset weights, My laptop can't train model, but I want to use this, please!

**Comment by Jamjamjamjon** [comment]
My email is 505024985@qq.com，send it for me if possible！Really appreciate that！

**Comment by wangermeng2021** [comment]
Download it from here: https://public.roboflow.com/ds/DXs6PTJ5Eo?key=DDgDEYXjLJ

**Comment by wangermeng2021** [comment]
Sorry, The weights has been removed.  if I have time ,I will retrain it

**Comment by Jamjamjamjon** [comment]
thanks.



发自我的iPhone


------------------ Original ------------------
From: wangermeng2021 ***@***.***&gt;
Date: Thu,Jun 24,2021 0:24 AM
To: wangermeng2021/Scaled-YOLOv4-tensorflow2 ***@***.***&gt;
Cc: Jamjamjamjon ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [wangermeng2021/Scaled-YOLOv4-tensorflow2] would you mind uploading the pothole datatset weights? (#7)





 
Sorry, The weights has been removed.  if I have time ,I will retrain it
